# Generated by Django 3.2.3 on 2021-06-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_image_fields_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cinema_images/', verbose_name='تصویر'),
        ),
    ]
